// GENERATED by scripts/generate-legacy-redirects.mjs — do not edit by hand.
// Regenerate with `pnpm redirects:legacy`.
//
// Legacy docs.arbitrum.io URLs (root-level) -> this site's /docs paths.
// Unportable entries are listed in redirects.legacy.todo.json.
/** @type {{ source: string, destination: string, permanent: boolean }[]} */
export const legacyRedirects = [
  {
    source: '/anytrust',
    destination: '/docs/how-arbitrum-works/deep-dives/anytrust-protocol',
    permanent: false,
  },
  {
    source: '/anytrust/inside-anytrust',
    destination: '/docs/how-arbitrum-works/deep-dives/anytrust-protocol',
    permanent: false,
  },
  {
    source: '/arbgas',
    destination: '/docs/how-arbitrum-works/deep-dives/gas-and-fees',
    permanent: false,
  },
  {
    source: '/arbos',
    destination: '/docs/how-arbitrum-works/reference/geth',
    permanent: false,
  },
  {
    source: '/arbos_formats',
    destination: '/docs/how-arbitrum-works/reference/geth',
    permanent: false,
  },
  {
    source: '/arbos/gas',
    destination: '/docs/how-arbitrum-works/deep-dives/gas-and-fees',
    permanent: false,
  },
  {
    source: '/arbos/gateways',
    destination: '/docs/how-arbitrum-works/inside-arbitrum-nitro',
    permanent: false,
  },
  {
    source: '/arbos/geth',
    destination: '/docs/how-arbitrum-works/reference/geth',
    permanent: false,
  },
  {
    source: '/arbos/introduction',
    destination: '/docs/how-arbitrum-works/reference/geth',
    permanent: false,
  },
  {
    source: '/arbos/l1-gas-pricing',
    destination: '/docs/how-arbitrum-works/deep-dives/gas-and-fees',
    permanent: false,
  },
  {
    source: '/arbos/l1-l2-messaging',
    destination: '/docs/how-arbitrum-works/deep-dives/l1-to-l2-messaging',
    permanent: false,
  },
  {
    source: '/arbos/l1-pricing',
    destination: '/docs/how-arbitrum-works/deep-dives/gas-and-fees',
    permanent: false,
  },
  {
    source: '/arbos/l1-to-l2-messaging',
    destination: '/docs/how-arbitrum-works/deep-dives/l1-to-l2-messaging',
    permanent: false,
  },
  {
    source: '/arbos/l2-l1-messaging',
    destination: '/docs/how-arbitrum-works/deep-dives/l2-to-l1-messaging',
    permanent: false,
  },
  {
    source: '/assertion-tree',
    destination: '/docs/how-arbitrum-works/deep-dives/assertions',
    permanent: false,
  },
  {
    source: '/avm_design',
    destination: '/docs/how-arbitrum-works/inside-arbitrum-nitro',
    permanent: false,
  },
  {
    source: '/avm_specification',
    destination: '/docs/how-arbitrum-works/inside-arbitrum-nitro',
    permanent: false,
  },
  {
    source: '/bold/bold-gentle-introduction',
    destination: '/docs/how-arbitrum-works/bold/gentle-introduction',
    permanent: false,
  },
  {
    source: '/bold/concepts/bold-technical-deep-dive',
    destination: '/docs/how-arbitrum-works/bold/bold-technical-deep-dive',
    permanent: false,
  },
  {
    source: '/bold/concepts/public-preview-expectations',
    destination: '/docs/how-arbitrum-works/bold/gentle-introduction',
    permanent: false,
  },
  {
    source: '/bridge-tokens/concepts/usdc-concept',
    destination: '/docs/arbitrum-bridge/usdc-arbitrum-one',
    permanent: false,
  },
  {
    source: '/build-decentralized-apps/arbitrum-vs-ethereum/block-numbers-and-time',
    destination: '/docs/arbitrum-essentials/arbitrum-vs-ethereum/block-numbers-and-time',
    permanent: false,
  },
  {
    source: '/build-decentralized-apps/arbitrum-vs-ethereum/comparison-overview',
    destination: '/docs/arbitrum-essentials/arbitrum-vs-ethereum/comparison-overview',
    permanent: false,
  },
  {
    source: '/build-decentralized-apps/arbitrum-vs-ethereum/nonce-management',
    destination: '/docs/arbitrum-essentials/arbitrum-vs-ethereum/nonce-management',
    permanent: false,
  },
  {
    source: '/build-decentralized-apps/arbitrum-vs-ethereum/rpc-methods',
    destination: '/docs/arbitrum-essentials/arbitrum-vs-ethereum/rpc-methods',
    permanent: false,
  },
  {
    source: '/build-decentralized-apps/arbitrum-vs-ethereum/solidity-support',
    destination: '/docs/arbitrum-essentials/arbitrum-vs-ethereum/solidity-support',
    permanent: false,
  },
  {
    source: '/build-decentralized-apps/bridging/configure-token-gateway/custom',
    destination: '/docs/arbitrum-essentials/bridging/configure-token-gateway/custom',
    permanent: false,
  },
  {
    source: '/build-decentralized-apps/bridging/configure-token-gateway/generic-custom',
    destination: '/docs/arbitrum-essentials/bridging/configure-token-gateway/generic-custom',
    permanent: false,
  },
  {
    source: '/build-decentralized-apps/bridging/configure-token-gateway/standard',
    destination: '/docs/arbitrum-essentials/bridging/configure-token-gateway/standard',
    permanent: false,
  },
  {
    source: '/build-decentralized-apps/bridging/cross-chain-messaging',
    destination: '/docs/arbitrum-essentials/bridging/cross-chain-messaging',
    permanent: false,
  },
  {
    source: '/build-decentralized-apps/bridging/custom-gas-token-chains',
    destination: '/docs/arbitrum-essentials/bridging/custom-gas-token-chains',
    permanent: false,
  },
  {
    source: '/build-decentralized-apps/bridging/deposit/eth-and-messages',
    destination: '/docs/arbitrum-essentials/bridging/deposit/eth-and-messages',
    permanent: false,
  },
  {
    source: '/build-decentralized-apps/bridging/deposit/tokens',
    destination: '/docs/arbitrum-essentials/bridging/deposit/tokens',
    permanent: false,
  },
  {
    source: '/build-decentralized-apps/bridging/l1-l3-teleportation',
    destination: '/docs/arbitrum-essentials/bridging/l1-l3-teleportation',
    permanent: false,
  },
  {
    source: '/build-decentralized-apps/bridging/overview',
    destination: '/docs/arbitrum-essentials/bridging/overview',
    permanent: false,
  },
  {
    source: '/build-decentralized-apps/bridging/withdraw/eth-and-messages',
    destination: '/docs/arbitrum-essentials/bridging/withdraw/eth-and-messages',
    permanent: false,
  },
  {
    source: '/build-decentralized-apps/bridging/withdraw/tokens',
    destination: '/docs/arbitrum-essentials/bridging/withdraw/tokens',
    permanent: false,
  },
  {
    source: '/build-decentralized-apps/how-to-estimate-gas',
    destination: '/docs/arbitrum-essentials/how-to-estimate-gas',
    permanent: false,
  },
  {
    source: '/build-decentralized-apps/how-to-get-l2block-on-l1',
    destination: '/docs/arbitrum-essentials/how-to-get-l2block-on-l1',
    permanent: false,
  },
  {
    source: '/build-decentralized-apps/nodeinterface/overview',
    destination: '/docs/arbitrum-essentials/nodeinterface/overview',
    permanent: false,
  },
  {
    source: '/build-decentralized-apps/nodeinterface/reference',
    destination: '/docs/arbitrum-essentials/nodeinterface/reference',
    permanent: false,
  },
  {
    source: '/build-decentralized-apps/precompiles/overview',
    destination: '/docs/arbitrum-essentials/precompiles/overview',
    permanent: false,
  },
  {
    source: '/build-decentralized-apps/precompiles/reference',
    destination: '/docs/arbitrum-essentials/precompiles/reference',
    permanent: false,
  },
  {
    source: '/build-decentralized-apps/public-chains',
    destination: '/docs/arbitrum-essentials/public-chains',
    permanent: false,
  },
  {
    source: '/build-decentralized-apps/quickstart-solidity-hardhat',
    destination: '/docs/build-decentralized-apps/quickstart-solidity-remix',
    permanent: false,
  },
  {
    source: '/build-decentralized-apps/reference/chain-params',
    destination: '/docs/arbitrum-essentials/reference/chain-params',
    permanent: false,
  },
  {
    source: '/build-decentralized-apps/reference/contract-addresses',
    destination: '/docs/arbitrum-essentials/reference/contract-addresses',
    permanent: false,
  },
  {
    source: '/build-decentralized-apps/reference/debugging-tools',
    destination: '/docs/arbitrum-essentials/reference/debugging-tools',
    permanent: false,
  },
  {
    source: '/build-decentralized-apps/reference/development-frameworks',
    destination: '/docs/arbitrum-essentials/reference/development-frameworks',
    permanent: false,
  },
  {
    source: '/build-decentralized-apps/reference/mainnet-risks',
    destination: '/docs/arbitrum-essentials/reference/mainnet-risks',
    permanent: false,
  },
  {
    source: '/build-decentralized-apps/reference/monitoring-tools-block-explorers',
    destination: '/docs/arbitrum-essentials/reference/monitoring-tools-block-explorers',
    permanent: false,
  },
  {
    source: '/build-decentralized-apps/reference/node-providers',
    destination: '/docs/arbitrum-essentials/reference/node-providers',
    permanent: false,
  },
  {
    source: '/build-decentralized-apps/reference/web3-libraries-tools',
    destination: '/docs/arbitrum-essentials/reference/web3-libraries-tools',
    permanent: false,
  },
  {
    source: '/build-decentralized-apps/token-bridging/token-bridge-erc20',
    destination: '/docs/how-arbitrum-works/deep-dives/token-bridging',
    permanent: false,
  },
  {
    source: '/build-decentralized-apps/troubleshooting',
    destination: '/docs/build-decentralized-apps/troubleshooting-building',
    permanent: false,
  },
  {
    source: '/censorship_resistance',
    destination: '/docs/how-arbitrum-works/deep-dives/sequencer',
    permanent: false,
  },
  {
    source: '/contract_deployment',
    destination: '/docs/build-decentralized-apps/quickstart-solidity-remix',
    permanent: false,
  },
  {
    source: '/developer_quickstart',
    destination: '/docs/get-started/overview',
    permanent: false,
  },
  {
    source: '/dispute_resolution',
    destination: '/docs/how-arbitrum-works/bold/gentle-introduction',
    permanent: false,
  },
  {
    source: '/faqs/faqs-index',
    destination: '/docs/get-started/faq',
    permanent: false,
  },
  {
    source: '/faqs/gas-faqs',
    destination: '/docs/get-started/faq',
    permanent: false,
  },
  {
    source: '/faqs/misc-faqs',
    destination: '/docs/get-started/faq',
    permanent: false,
  },
  {
    source: '/faqs/nodes-faqs',
    destination: '/docs/run-a-node/faq',
    permanent: false,
  },
  {
    source: '/faqs/protocol-faqs',
    destination: '/docs/get-started/faq',
    permanent: false,
  },
  {
    source: '/faqs/the-merge',
    destination: '/docs/get-started/overview',
    permanent: false,
  },
  {
    source: '/faqs/tooling-faqs',
    destination: '/docs/build-decentralized-apps/troubleshooting-building',
    permanent: false,
  },
  {
    source: '/faqs/x-chain-faqs',
    destination: '/docs/get-started/faq',
    permanent: false,
  },
  {
    source: '/finality',
    destination: '/docs/how-arbitrum-works/deep-dives/transaction-lifecycle',
    permanent: false,
  },
  {
    source: '/for-devs/gentle-introduction-dapps',
    destination: '/docs/get-started/arbitrum-introduction',
    permanent: false,
  },
  {
    source: '/for-devs/quickstart-solidity-hardhat',
    destination: '/docs/build-decentralized-apps/quickstart-solidity-remix',
    permanent: false,
  },
  {
    source: '/for-devs/quickstart-solidity-remix',
    destination: '/docs/build-decentralized-apps/quickstart-solidity-remix',
    permanent: false,
  },
  {
    source: '/for-users/troubleshooting-users',
    destination: '/docs/arbitrum-bridge/troubleshooting',
    permanent: false,
  },
  {
    source: '/fraud-proofs/challenge-manager',
    destination: '/docs/how-arbitrum-works/bold/gentle-introduction',
    permanent: false,
  },
  {
    source: '/fraud-proofs/osp-assumptions',
    destination: '/docs/how-arbitrum-works/bold/gentle-introduction',
    permanent: false,
  },
  {
    source: '/fraud-proofs/wasm-wavm',
    destination: '/docs/how-arbitrum-works/bold/gentle-introduction',
    permanent: false,
  },
  {
    source: '/fraud-proofs/wavm-custom-opcodes',
    destination: '/docs/how-arbitrum-works/bold/gentle-introduction',
    permanent: false,
  },
  {
    source: '/fraud-proofs/wavm-floats',
    destination: '/docs/how-arbitrum-works/bold/gentle-introduction',
    permanent: false,
  },
  {
    source: '/fraud-proofs/wavm-modules',
    destination: '/docs/how-arbitrum-works/bold/gentle-introduction',
    permanent: false,
  },
  {
    source: '/frontend_integration',
    destination: '/docs/build-decentralized-apps/quickstart-solidity-remix',
    permanent: false,
  },
  {
    source: '/get-started/get-started',
    destination: '/docs/get-started/overview',
    permanent: false,
  },
  {
    source: '/getting-started-devs',
    destination: '/docs/build-decentralized-apps/quickstart-solidity-remix',
    permanent: false,
  },
  {
    source: '/getting-started-users',
    destination: '/docs/arbitrum-bridge/quickstart',
    permanent: false,
  },
  {
    source: '/how-arbitrum-works',
    destination: '/docs/how-arbitrum-works/inside-arbitrum-nitro',
    permanent: false,
  },
  {
    source: '/how-arbitrum-works/a-gentle-introduction',
    destination: '/docs/how-arbitrum-works/inside-arbitrum-nitro',
    permanent: false,
  },
  {
    source: '/how-arbitrum-works/anytrust-protocol',
    destination: '/docs/how-arbitrum-works/deep-dives/anytrust-protocol',
    permanent: false,
  },
  {
    source: '/how-arbitrum-works/arbos/geth',
    destination: '/docs/how-arbitrum-works/reference/geth',
    permanent: false,
  },
  {
    source: '/how-arbitrum-works/arbos/introduction',
    destination: '/docs/how-arbitrum-works/deep-dives/arbos',
    permanent: false,
  },
  {
    source: '/how-arbitrum-works/arbos/l1-l2-messaging',
    destination: '/docs/how-arbitrum-works/deep-dives/l1-to-l2-messaging',
    permanent: false,
  },
  {
    source: '/how-arbitrum-works/arbos/l2-l1-messaging',
    destination: '/docs/how-arbitrum-works/deep-dives/l2-to-l1-messaging',
    permanent: false,
  },
  {
    source: '/how-arbitrum-works/assertion-tree',
    destination: '/docs/how-arbitrum-works/deep-dives/assertions',
    permanent: false,
  },
  {
    source: '/how-arbitrum-works/bold/public-preview-expectations',
    destination: '/docs/how-arbitrum-works/bold/gentle-introduction',
    permanent: false,
  },
  {
    source: '/how-arbitrum-works/data-availability',
    destination: '/docs/run-a-node/data-availability',
    permanent: false,
  },
  {
    source: '/how-arbitrum-works/fees',
    destination: '/docs/how-arbitrum-works/deep-dives/gas-and-fees',
    permanent: false,
  },
  {
    source: '/how-arbitrum-works/fraud-proofs/challenge-manager',
    destination: '/docs/how-arbitrum-works/bold/gentle-introduction',
    permanent: false,
  },
  {
    source: '/how-arbitrum-works/fraud-proofs/osp-assumptions',
    destination: '/docs/how-arbitrum-works/bold/gentle-introduction',
    permanent: false,
  },
  {
    source: '/how-arbitrum-works/fraud-proofs/wasm-to-wavm',
    destination: '/docs/how-arbitrum-works/bold/gentle-introduction',
    permanent: false,
  },
  {
    source: '/how-arbitrum-works/fraud-proofs/wavm-custom-opcodes',
    destination: '/docs/how-arbitrum-works/bold/gentle-introduction',
    permanent: false,
  },
  {
    source: '/how-arbitrum-works/gas-fees',
    destination: '/docs/how-arbitrum-works/deep-dives/gas-and-fees',
    permanent: false,
  },
  {
    source: '/how-arbitrum-works/inside-anytrust',
    destination: '/docs/how-arbitrum-works/deep-dives/anytrust-protocol',
    permanent: false,
  },
  {
    source: '/how-arbitrum-works/interactive-fraud-proofs',
    destination: '/docs/how-arbitrum-works/bold/gentle-introduction',
    permanent: false,
  },
  {
    source: '/how-arbitrum-works/l1-gas-pricing',
    destination: '/docs/how-arbitrum-works/deep-dives/gas-and-fees',
    permanent: false,
  },
  {
    source: '/how-arbitrum-works/l1-pricing',
    destination: '/docs/how-arbitrum-works/deep-dives/gas-and-fees',
    permanent: false,
  },
  {
    source: '/how-arbitrum-works/l1-to-l2-messaging',
    destination: '/docs/how-arbitrum-works/deep-dives/l1-to-l2-messaging',
    permanent: false,
  },
  {
    source: '/how-arbitrum-works/l2-to-l1-messaging',
    destination: '/docs/how-arbitrum-works/deep-dives/l2-to-l1-messaging',
    permanent: false,
  },
  {
    source: '/how-arbitrum-works/nitro-vs-classic',
    destination: '/docs/how-arbitrum-works/inside-arbitrum-nitro',
    permanent: false,
  },
  {
    source: '/how-arbitrum-works/optimistic-rollup',
    destination: '/docs/how-arbitrum-works/inside-arbitrum-nitro',
    permanent: false,
  },
  {
    source: '/how-arbitrum-works/separating-execution-from-proving',
    destination: '/docs/how-arbitrum-works/bold/gentle-introduction',
    permanent: false,
  },
  {
    source: '/how-arbitrum-works/sequencer',
    destination: '/docs/how-arbitrum-works/deep-dives/sequencer',
    permanent: false,
  },
  {
    source: '/how-arbitrum-works/state-transition-function/arbos',
    destination: '/docs/how-arbitrum-works/deep-dives/arbos',
    permanent: false,
  },
  {
    source: '/how-arbitrum-works/state-transition-function/modified-geth-on-arbitrum',
    destination: '/docs/how-arbitrum-works/reference/geth',
    permanent: false,
  },
  {
    source: '/how-arbitrum-works/state-transition-function/stf-inputs',
    destination: '/docs/how-arbitrum-works/reference/stf-inputs',
    permanent: false,
  },
  {
    source: '/how-arbitrum-works/timeboost',
    destination: '/docs/how-arbitrum-works/timeboost/gentle-introduction',
    permanent: false,
  },
  {
    source: '/how-arbitrum-works/transaction-lifecycle',
    destination: '/docs/how-arbitrum-works/deep-dives/transaction-lifecycle',
    permanent: false,
  },
  {
    source: '/how-arbitrum-works/tx-lifecycle',
    destination: '/docs/how-arbitrum-works/deep-dives/transaction-lifecycle',
    permanent: false,
  },
  {
    source: '/how-arbitrum-works/validation-and-proving/proving-and-challenges',
    destination: '/docs/how-arbitrum-works/bold/gentle-introduction',
    permanent: false,
  },
  {
    source: '/how-arbitrum-works/validation-and-proving/rollup-protocol',
    destination: '/docs/how-arbitrum-works/inside-arbitrum-nitro',
    permanent: false,
  },
  {
    source: '/how-arbitrum-works/validation-and-proving/validation-and-proving',
    destination: '/docs/how-arbitrum-works/bold/gentle-introduction',
    permanent: false,
  },
  {
    source: '/how-arbitrum-works/why-nitro',
    destination: '/docs/how-arbitrum-works/inside-arbitrum-nitro',
    permanent: false,
  },
  {
    source: '/inside_arbitrum',
    destination: '/docs/how-arbitrum-works/inside-arbitrum-nitro',
    permanent: false,
  },
  {
    source: '/inside-anytrust',
    destination: '/docs/how-arbitrum-works/deep-dives/anytrust-protocol',
    permanent: false,
  },
  {
    source: '/inside-arbitrum-nitro',
    destination: '/docs/how-arbitrum-works/inside-arbitrum-nitro',
    permanent: false,
  },
  {
    source: '/installation',
    destination: '/docs/run-a-node/run-full-node',
    permanent: false,
  },
  {
    source: '/intro',
    destination: '/docs/get-started/arbitrum-introduction',
    permanent: false,
  },
  {
    source: '/l1_l2_messages',
    destination: '/docs/how-arbitrum-works/deep-dives/l1-to-l2-messaging',
    permanent: false,
  },
  {
    source: '/launch-arbitrum-chain/chain-config/costs/calculate-aep-fees',
    destination: 'https://docs.arbitrum.foundation/calculate-aep-fees',
    permanent: false,
  },
  {
    source:
      '/launch-arbitrum-chain/configure-your-chain/advanced-configurations/aep-fee-router/calculate-aep-fees',
    destination: 'https://docs.arbitrum.foundation/calculate-aep-fees',
    permanent: false,
  },
  {
    source:
      '/launch-arbitrum-chain/configure-your-chain/advanced-configurations/configure-aep-fee-routing/calculate-aep-fees',
    destination: 'https://docs.arbitrum.foundation/calculate-aep-fees',
    permanent: false,
  },
  {
    source: '/launch-arbitrum-chain/configure-your-chain/common/aep-fees/calculate-aep-fees',
    destination: 'https://docs.arbitrum.foundation/calculate-aep-fees',
    permanent: false,
  },
  {
    source:
      '/launch-arbitrum-chain/configure-your-chain/common/validation-and-security/arbos-upgrade',
    destination: '/docs/launch-arbitrum-chain/operate/arbos-upgrade',
    permanent: false,
  },
  {
    source: '/launch-arbitrum-chain/deploy-an-arbitrum-chain/canonical-factory-contracts',
    destination: '/docs/launch-arbitrum-chain/deploy/canonical-factory-contracts',
    permanent: false,
  },
  {
    source: '/launch-arbitrum-chain/ecosystem-support/add-arbitrum-chain-to-bridge-ui',
    destination: '/docs/launch-arbitrum-chain/integrations/bridge-ui',
    permanent: false,
  },
  {
    source: '/launch-arbitrum-chain/features/common/configure-aep/configure-aep-fees',
    destination: 'https://docs.arbitrum.foundation/calculate-aep-fees',
    permanent: false,
  },
  {
    source: '/launch-arbitrum-chain/maintain-your-chain/guidance/key-rotation',
    destination: '/docs/launch-arbitrum-chain/operate/key-rotation',
    permanent: false,
  },
  {
    source: '/launch-arbitrum-chain/maintain-your-chain/guidance/state-growth',
    destination: '/docs/launch-arbitrum-chain/operate/state-growth',
    permanent: false,
  },
  {
    source:
      '/launch-orbit-chain/configure-your-chain/advanced-configurations/aep-fee-router/calculate-aep-fees',
    destination: 'https://docs.arbitrum.foundation/calculate-aep-fees',
    permanent: false,
  },
  {
    source: '/launch-orbit-chain/configure-your-chain/common-configurations/calculate-aep-fees',
    destination: 'https://docs.arbitrum.foundation/calculate-aep-fees',
    permanent: false,
  },
  {
    source: '/launch-orbit-chain/how-tos/calculate-aep-fees',
    destination: 'https://docs.arbitrum.foundation/calculate-aep-fees',
    permanent: false,
  },
  {
    source: '/launch-orbit-chain/infra-options-orbit-chains',
    destination: '/docs/launch-arbitrum-chain/third-party-integrations/third-party-providers',
    permanent: false,
  },
  {
    source: '/launch-orbit-chain/third-party-integrations/integrations',
    destination: '/docs/launch-arbitrum-chain/third-party-integrations/third-party-providers',
    permanent: false,
  },
  {
    source: '/launch-orbit-chain/third-party-integrations/third-party-providers',
    destination: '/docs/launch-arbitrum-chain/third-party-integrations/third-party-providers',
    permanent: false,
  },
  {
    source: '/learn-more',
    destination: '/docs/get-started/faq',
    permanent: false,
  },
  {
    source: '/learnmore/faq',
    destination: '/docs/get-started/faq',
    permanent: false,
  },
  {
    source: '/migration/state-migration',
    destination: '/docs/run-a-node/nitro/migrate-state-and-history-from-classic',
    permanent: false,
  },
  {
    source: '/node-running/build-nitro-locally',
    destination: '/docs/run-a-node/nitro/build-nitro-locally',
    permanent: false,
  },
  {
    source: '/node-running/command-line-options',
    destination: '/docs/run-a-node/run-full-node',
    permanent: false,
  },
  {
    source: '/node-running/gentle-introduction-run-node',
    destination: '/docs/run-a-node/overview',
    permanent: false,
  },
  {
    source: '/node-running/how-tos/build-nitro-locally',
    destination: '/docs/run-a-node/nitro/build-nitro-locally',
    permanent: false,
  },
  {
    source: '/node-running/how-tos/migrate-state-and-history-from-classic',
    destination: '/docs/run-a-node/nitro/migrate-state-and-history-from-classic',
    permanent: false,
  },
  {
    source: '/node-running/how-tos/read-sequencer-feed',
    destination: '/docs/run-a-node/sequencer/read-sequencer-feed',
    permanent: false,
  },
  {
    source: '/node-running/how-tos/running-a-classic-node',
    destination: '/docs/run-a-node/more-types/run-classic-node',
    permanent: false,
  },
  {
    source: '/node-running/how-tos/running-a-feed-relay',
    destination: '/docs/run-a-node/run-feed-relay',
    permanent: false,
  },
  {
    source: '/node-running/how-tos/running-a-full-node',
    destination: '/docs/run-a-node/run-full-node',
    permanent: false,
  },
  {
    source: '/node-running/how-tos/running-a-node',
    destination: '/docs/run-a-node/run-full-node',
    permanent: false,
  },
  {
    source: '/node-running/how-tos/running-a-sequencer-coordinator-manager',
    destination: '/docs/run-a-node/sequencer/run-sequencer-coordination-manager',
    permanent: false,
  },
  {
    source: '/node-running/how-tos/running-a-validator',
    destination: '/docs/run-a-node/more-types/run-validator-node',
    permanent: false,
  },
  {
    source: '/node-running/how-tos/running-an-archive-node',
    destination: '/docs/run-a-node/more-types/run-archive-node',
    permanent: false,
  },
  {
    source: '/node-running/how-tos/running-an-orbit-node',
    destination: '/docs/run-a-node/run-full-node',
    permanent: false,
  },
  {
    source: '/node-running/quickstart-running-a-node',
    destination: '/docs/run-a-node/overview',
    permanent: false,
  },
  {
    source: '/node-running/read-sequencer-feed',
    destination: '/docs/run-a-node/sequencer/read-sequencer-feed',
    permanent: false,
  },
  {
    source: '/node-running/reference/arbos-software-releases/arbos11',
    destination: '/docs/run-a-node/arbos-releases/arbos11',
    permanent: false,
  },
  {
    source: '/node-running/reference/arbos-software-releases/arbos20',
    destination: '/docs/run-a-node/arbos-releases/arbos20',
    permanent: false,
  },
  {
    source: '/node-running/reference/arbos-software-releases/overview',
    destination: '/docs/run-a-node/arbos-releases/overview',
    permanent: false,
  },
  {
    source: '/node-running/reference/ethereum-beacon-rpc-providers',
    destination: '/docs/run-a-node/l1-ethereum-beacon-chain-rpc-providers',
    permanent: false,
  },
  {
    source: '/node-running/reference/software-releases',
    destination: '/docs/run-a-node/arbos-releases/overview',
    permanent: false,
  },
  {
    source: '/node-running/running-a-classic-node',
    destination: '/docs/run-a-node/more-types/run-classic-node',
    permanent: false,
  },
  {
    source: '/node-running/running-a-feed-relay',
    destination: '/docs/run-a-node/run-feed-relay',
    permanent: false,
  },
  {
    source: '/node-running/running-a-node',
    destination: '/docs/run-a-node/run-full-node',
    permanent: false,
  },
  {
    source: '/node-running/running-a-validator',
    destination: '/docs/run-a-node/more-types/run-validator-node',
    permanent: false,
  },
  {
    source: '/node-running/running-an-archive-node',
    destination: '/docs/run-a-node/more-types/run-archive-node',
    permanent: false,
  },
  {
    source: '/node-running/troubleshooting-running-nodes',
    destination: '/docs/run-a-node/troubleshooting',
    permanent: false,
  },
  {
    source: '/notices/arbos-50',
    destination: '/docs/notices/arbos51-upgrade-notice',
    permanent: false,
  },
  {
    source: '/notices/arbos-fusaka',
    destination: '/docs/notices/fusaka-upgrade-notice',
    permanent: false,
  },
  {
    source: '/notices/arbos51-arbsepolia-upgrade-notice',
    destination: '/docs/notices/arbos51-upgrade-notice',
    permanent: false,
  },
  {
    source: '/proving/challenge-manager',
    destination: '/docs/how-arbitrum-works/bold/gentle-introduction',
    permanent: false,
  },
  {
    source: '/proving/osp-assumptions',
    destination: '/docs/how-arbitrum-works/bold/gentle-introduction',
    permanent: false,
  },
  {
    source: '/proving/wasm-to-wavm',
    destination: '/docs/how-arbitrum-works/bold/gentle-introduction',
    permanent: false,
  },
  {
    source: '/proving/wavm-custom-opcodes',
    destination: '/docs/how-arbitrum-works/bold/gentle-introduction',
    permanent: false,
  },
  {
    source: '/proving/wavm-floats',
    destination: '/docs/how-arbitrum-works/bold/gentle-introduction',
    permanent: false,
  },
  {
    source: '/proving/wavm-modules',
    destination: '/docs/how-arbitrum-works/bold/gentle-introduction',
    permanent: false,
  },
  {
    source: '/quickstart',
    destination: '/docs/build-decentralized-apps/quickstart-solidity-remix',
    permanent: false,
  },
  {
    source: '/rollup_basics',
    destination: '/docs/get-started',
    permanent: false,
  },
  {
    source: '/rollup_protocol',
    destination: '/docs/how-arbitrum-works/inside-arbitrum-nitro',
    permanent: false,
  },
  {
    source: '/run-arbitrum-node/arbos-releases/arbos30',
    destination: '/docs/run-a-node/arbos-releases/arbos32',
    permanent: false,
  },
  {
    source: '/run-arbitrum-node/arbos-releases/arbos31',
    destination: '/docs/run-a-node/arbos-releases/arbos32',
    permanent: false,
  },
  {
    source: '/run-arbitrum-node/arbos-releases/arbos50',
    destination: '/docs/run-a-node/arbos-releases/arbos51',
    permanent: false,
  },
  {
    source: '/run-arbitrum-node/how-to-use-timeboost',
    destination: '/docs/how-arbitrum-works/timeboost/how-to-use-timeboost',
    permanent: false,
  },
  {
    source: '/run-arbitrum-node/node-types',
    destination: '/docs/run-a-node/overview',
    permanent: false,
  },
  {
    source: '/run-arbitrum-node/quickstart',
    destination: '/docs/run-a-node/overview',
    permanent: false,
  },
  {
    source: '/run-arbitrum-node/run-local-dev-node',
    destination: '/docs/run-a-node/run-local-full-chain-simulation',
    permanent: false,
  },
  {
    source: '/run-arbitrum-node/sequencer/run-feed-relay',
    destination: '/docs/run-a-node/run-feed-relay',
    permanent: false,
  },
  {
    source: '/running_goerli_nitro_node',
    destination: '/docs/run-a-node/run-full-node',
    permanent: false,
  },
  {
    source: '/running_nitro_node',
    destination: '/docs/run-a-node/run-full-node',
    permanent: false,
  },
  {
    source: '/running_node',
    destination: '/docs/run-a-node/run-full-node',
    permanent: false,
  },
  {
    source: '/running_rinkeby_nitro_node',
    destination: '/docs/run-a-node/run-full-node',
    permanent: false,
  },
  {
    source: '/sequencer',
    destination: '/docs/how-arbitrum-works/deep-dives/sequencer',
    permanent: false,
  },
  {
    source: '/stylus',
    destination: '/docs/stylus/gentle-introduction',
    permanent: false,
  },
  {
    source: '/stylus-by-example/abi_decode',
    destination:
      'https://github.com/OffchainLabs/stylus-by-example/tree/master/example_code/basic_examples/abi_decode',
    permanent: false,
  },
  {
    source: '/stylus-by-example/abi_encode',
    destination:
      'https://github.com/OffchainLabs/stylus-by-example/tree/master/example_code/basic_examples/abi_encode',
    permanent: false,
  },
  {
    source: '/stylus-by-example/bytes_in_bytes_out',
    destination:
      'https://github.com/OffchainLabs/stylus-by-example/tree/master/example_code/applications',
    permanent: false,
  },
  {
    source: '/stylus-by-example/errors',
    destination:
      'https://github.com/OffchainLabs/stylus-by-example/tree/master/example_code/basic_examples/errors',
    permanent: false,
  },
  {
    source: '/stylus-by-example/events',
    destination:
      'https://github.com/OffchainLabs/stylus-by-example/tree/master/example_code/basic_examples/events',
    permanent: false,
  },
  {
    source: '/stylus-by-example/function',
    destination:
      'https://github.com/OffchainLabs/stylus-by-example/tree/master/example_code/basic_examples/function',
    permanent: false,
  },
  {
    source: '/stylus-by-example/function_selector',
    destination:
      'https://github.com/OffchainLabs/stylus-by-example/tree/master/example_code/applications',
    permanent: false,
  },
  {
    source: '/stylus-by-example/hashing',
    destination:
      'https://github.com/OffchainLabs/stylus-by-example/tree/master/example_code/applications',
    permanent: false,
  },
  {
    source: '/stylus-by-example/hello_world',
    destination:
      'https://github.com/OffchainLabs/stylus-by-example/tree/master/example_code/basic_examples/hello_world',
    permanent: false,
  },
  {
    source: '/stylus-by-example/inheritance',
    destination:
      'https://github.com/OffchainLabs/stylus-by-example/tree/master/example_code/applications',
    permanent: false,
  },
  {
    source: '/stylus-by-example/primitive_data_types',
    destination:
      'https://github.com/OffchainLabs/stylus-by-example/tree/master/example_code/basic_examples/primitive_data_types',
    permanent: false,
  },
  {
    source: '/stylus-by-example/sending_ether',
    destination:
      'https://github.com/OffchainLabs/stylus-by-example/tree/master/example_code/basic_examples/sending_ether',
    permanent: false,
  },
  {
    source: '/stylus-by-example/variables',
    destination:
      'https://github.com/OffchainLabs/stylus-by-example/tree/master/example_code/basic_examples/variables',
    permanent: false,
  },
  {
    source: '/stylus/concepts/public-preview-expectations',
    destination: '/docs/stylus/gentle-introduction',
    permanent: false,
  },
  {
    source: '/stylus/concepts/stylus-cache-manager',
    destination: '/docs/stylus/how-tos/caching-contracts',
    permanent: false,
  },
  {
    source: '/stylus/concepts/stylus-gas',
    destination: '/docs/stylus/concepts/gas-metering',
    permanent: false,
  },
  {
    source: '/stylus/how-tos/adding-support-for-new-languages',
    destination: '/docs/stylus/how-tos/deploying-non-rust-wasm-contracts',
    permanent: false,
  },
  {
    source: '/stylus/how-tos/cache-contracts',
    destination: '/docs/stylus/how-tos/caching-contracts',
    permanent: false,
  },
  {
    source: '/stylus/how-tos/local-stylus-dev-node',
    destination: '/docs/run-a-node/run-nitro-dev-node',
    permanent: false,
  },
  {
    source: '/stylus/reference/cargo-stylus',
    destination: '/docs/stylus/gentle-introduction',
    permanent: false,
  },
  {
    source: '/stylus/rust-sdk-guide',
    destination: '/docs/stylus/reference/rust-sdk-guide',
    permanent: false,
  },
  {
    source: '/stylus/stylus-gentle-introduction',
    destination: '/docs/stylus/gentle-introduction',
    permanent: false,
  },
  {
    source: '/stylus/stylus-quickstart',
    destination: '/docs/stylus/quickstart',
    permanent: false,
  },
  {
    source: '/stylus/using-cli',
    destination: '/docs/stylus/cli-tools/overview',
    permanent: false,
  },
  {
    source: '/tutorials',
    destination: '/docs/build-decentralized-apps/quickstart-solidity-remix',
    permanent: false,
  },
  {
    source: '/tx_lifecycle',
    destination: '/docs/how-arbitrum-works/deep-dives/transaction-lifecycle',
    permanent: false,
  },
  {
    source: '/tx-lifecycle',
    destination: '/docs/how-arbitrum-works/deep-dives/transaction-lifecycle',
    permanent: false,
  },
  {
    source: '/txlifecycle',
    destination: '/docs/how-arbitrum-works/deep-dives/transaction-lifecycle',
    permanent: false,
  },
  {
    source: '/welcome',
    destination: '/docs/get-started/overview',
    permanent: false,
  },
  {
    source: '/welcome/arbitrum-gentle-introduction',
    destination: '/docs/get-started/arbitrum-introduction',
    permanent: false,
  },
  {
    source: '/welcome/get-started',
    destination: '/docs/get-started/overview',
    permanent: true,
  },
  {
    source: '/why-nitro',
    destination: '/docs/how-arbitrum-works/inside-arbitrum-nitro',
    permanent: false,
  },
  {
    source: '/withdrawals',
    destination: '/docs/how-arbitrum-works/deep-dives/transaction-lifecycle',
    permanent: false,
  },
];
